name: Pull Requests
on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.6.5
      - uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run -r ci
